# Wprowadzenie do narzędzi

Jeśli pracujesz w Google Colab: sprawdź, czy masz ustawiony prawidłowy typ środowiska wykonawczego (R). Jeśli w VSC sprawdź, czy masz ustawione jądro RKernel.

**Aby uruchomić kod kliknij we fragment kodu i wciśnij Ctrl+Enter**


## Podstawy podstaw R

(Pomiń, jeśli wiesz cokolwiek o R). R jest jednym z najpopularniejszych (obok Pythona) językiem wykorzystywanym w szeroko rozumianej Data Science.

### Typy zmiennych i konwersje typów

In [1]:
# Utwórz zmienną temp i przypisz jej wartość "36.6". Następnie wyświetl jej wartość.

temp <- "36.6"
temp

[1] "36.6"

In [2]:
# Spróbuj dodać do stworzonej zmiennej wartość 0.1. Zwróć uwagę na komunikat.

# temp + 0.1

In [3]:
# Sprawdź jakiego typu jest zmienna temp.

class(temp)

[1] "character"

In [4]:
# Przekonwertuj zmienną na typ numeric, a następnie sprawdź jej wartość. Zwróć uwagę jak zmienił się sposób jej wyświetlania.

temp <- as.numeric(temp)
temp

[1] 36.6

In [5]:
# Przekonwertuj zmienną na typ integer, a następnie sprawdź jej wartość.

temp <- as.integer(temp)
temp

[1] 36

In [6]:
# Sprawdź typy zmiennych dla następujących wartości:

class("36")

[1] "character"

In [7]:
class(36)

[1] "numeric"

In [8]:
class(36L)

[1] "integer"

In [9]:
class(36+0i)

[1] "complex"

In [10]:
class(TRUE)

[1] "logical"

### Wektory

Jedynka w nawiasach kwadratowych przy każdym wyniku bierze się z faktu, że w języku R pojedyncze liczby są wektorami. Oznacza ona indeks w wektorze. Wszystkie elementy wektora muszą być tego samego typu atomowego (np. liczbowe, znakowe, logiczne). Jeżeli warunek ten nie jest spełniony, to system wykona konwersję do wspólnego typu.

Ponadto, wykonując operacje na dwóch wektorach o różnych rozmiarach - wektor o mniejszym rozmiarze jest cyklicznie powielany.

Wektory można definiować na kilka różnych sposobów, np.:

In [11]:
x <- c(2, 5, 8)
c(2:4, c(5, 8))

[1] 2 3 4 5 8

In [12]:
2:5

[1] 2 3 4 5

In [13]:
seq(2, 5, by = 0.75)

[1] 2.00 2.75 3.50 4.25 5.00

In [14]:
rep(x, times = 3)

[1] 2 5 8 2 5 8 2 5 8

In [15]:
rep(x, each = 3)

[1] 2 2 2 5 5 5 8 8 8

In [16]:
# Stwórz wektor w1 używając sekwencji i wypisz jego wartość.

w1 <- 3:0
w1

[1] 3 2 1 0

In [17]:
# Sprawdź, w jaki sposób wyświetlić wybrane elementy wektora, wpisując poniższe wyrażenia:

w1[1]

[1] 3

In [18]:
w1[length(w1)]

[1] 0

In [19]:
w1[c(T, T, T, F)]

[1] 3 2 1

In [20]:
w1[3:1]

[1] 1 2 3

In [21]:
w1[-2]

[1] 3 1 0

In [22]:
# inny sposib na uzyskanie ostatniego elementu w wektorze
tail(w1, n=1)

[1] 0

In [23]:
# Stwórz poniższe wektory, używając funkcji c(), a następnie sprawdź ich typ oraz wartość.

w2 <- c(0/0, 1/0, 1/Inf, TRUE, as.numeric("abc"))
w3 <- as.logical(c("T", "False", "abc"))

Warning message:
“NAs introduced by coercion”


In [24]:
w2

[1] NaN Inf   0   1  NA

In [25]:
w3

[1]  TRUE FALSE    NA

Zwróć szczególną uwagę na wartości _NA_ oraz _NaN_. Co oznaczają?

In [26]:
# Stwórz pusty wektor używając funkcji vector(). Przypisz do niego wartości 1, 2, 3, 4, "null", 5, 6, 7, 8, 9.
# Jakiego typu są dane znajdujące się w wektorze po przypisaniu wartości?
# Przekonwertuj wektor na wektor o wartościach typu numeric, a następnie usuń wartość _NA_ z wektora.
w4 <- vector("numeric", length = 9)
w4

[1] 0 0 0 0 0 0 0 0 0

In [27]:
w4[1:4] <- 1:4
w4[5] <- "null"
w4[6:9] <- 6:9
w4

[1] "1"    "2"    "3"    "4"    "null" "6"    "7"    "8"    "9"

In [28]:
class(w4)

[1] "character"

In [29]:
w4 <- as.numeric(w4)
w4

Warning message:
“NAs introduced by coercion”


[1]  1  2  3  4 NA  6  7  8  9

In [30]:
w4 <- w4[!is.na(w4)]
w4

[1] 1 2 3 4 6 7 8 9

In [31]:
# Stwórz wektory w5 oraz w6, a następnie sprawdź wyniki poniższych wyrażeń:

w5 <- 1:5
w5

[1] 1 2 3 4 5

In [32]:
w6 <- 6:10
w6

[1]  6  7  8  9 10

In [33]:
w5 + w6

[1]  7  9 11 13 15

In [34]:
w5 - w6

[1] -5 -5 -5 -5 -5

In [35]:
w5 * w6

[1]  6 14 24 36 50

In [36]:
w5 / w6

[1] 0.1666667 0.2857143 0.3750000 0.4444444 0.5000000

In [37]:
w5 == w6

[1] FALSE FALSE FALSE FALSE FALSE

In [38]:
w5 >= 3

[1] FALSE FALSE  TRUE  TRUE  TRUE

### Macierze

Macierz jest obiektem dwuwymiarowym oraz, podobnie jak wektor, jest homogeniczna. Najprostszym sposobem utworzenia macierzy, jest użycie funkcji `matrix()`.

In [39]:
macierz1 <- matrix(1:12, 3, 4)

In [40]:
# Wyświetl macierz macierz1, a następnie wyświetl element znajdujący się na pozycji 1, 2.
# Czy pierwsza wartość określa wiersz, czy kolumnę? Jak wpływa na wynik parametr drop = FALSE?

macierz1

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [41]:
macierz1[1, 2]

[1] 4

In [42]:
macierz1[1, 2, drop=FALSE]

[,1]
[1,] 4

In [43]:
# Wyświetl 2 i 3 wiersz macierzy.
macierz1[2:3,]

[,1] [,2] [,3] [,4]
[1,] 2    5    8    11  
[2,] 3    6    9    12

In [44]:
# Wywołaj poniższy kod. Do czego służą funkcje diag() oraz solve()?
diag(macierz1)

[1] 1 5 9

In [45]:
diag(5)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

In [46]:
macierz2 <- diag(1:3)
macierz2

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [47]:
solve(macierz2)

[,1] [,2] [,3]     
[1,] 1    0.0  0.0000000
[2,] 0    0.5  0.0000000
[3,] 0    0.0  0.3333333

In [48]:
# Stwórz 12 elementowy wektor, a następnie wykorzystaj go do stworzenia macierzy o 3 wierszach i 4 kolumnach.
# Zwróć uwagę, w jaki sposób zostały wpisane wartości do macierzy. Sprawdź atrybuty macierzy macierz3.
# Porównaj wynik z macierzą macierz1.
macierz3 <- 1:12
macierz3

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [49]:
dim(macierz3) <- c(3, 4)
macierz3

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [50]:
attributes(macierz3)

$dim
[1] 3 4

In [51]:
macierz1
macierz3

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [52]:
macierz1 == macierz3

[,1] [,2] [,3] [,4]
[1,] TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE

In [53]:
all(macierz1 == macierz3)

[1] TRUE

In [54]:
# Utwórz nową macierz, ustawiając argument byrow=TRUE. Porównaj ją z macierz1.
macierz4 <- matrix(1:12, 3, 4, byrow = TRUE)
macierz4

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [55]:
# Utwórz nowe dwie macierze z macierz1 i macierz4, stosując kolejno funkcje cbind() oraz rbind().
# Zwróć uwagę na różnice w działaniu obu funkcji

macierz5 <- cbind(macierz1, macierz4)
macierz5

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    4    7    10   1     2    3    4  
[2,] 2    5    8    11   5     6    7    8  
[3,] 3    6    9    12   9    10   11   12

In [56]:
macierz6 <- rbind(macierz1, macierz4)
macierz6

[,1] [,2] [,3] [,4]
[1,] 1     4    7   10  
[2,] 2     5    8   11  
[3,] 3     6    9   12  
[4,] 1     2    3    4  
[5,] 5     6    7    8  
[6,] 9    10   11   12

### Listy

W odróżnieniu od wektorów i macierzy, listy mogą przechowywać obiekty różnego typu, w określonej kolejności.

In [57]:
# Stwórz listę używając funkcji list(). Sprawdź typ zmiennej oraz poszczególnych elementów.

lista1 <- list(lp = 1L, imie = "Jan", nazwisko = "Kowalski", oceny = c(4.0, 3.5, 5.0))
lista1

$lp
[1] 1

$imie
[1] "Jan"

$nazwisko
[1] "Kowalski"

$oceny
[1] 4.0 3.5 5.0

In [58]:
# Sprawdź różne sposoby dostępu do elementow listy i możliwości jej modyfikacji.
# Zwróć uwagę na różnicę w stosowaniu pojedynczych lub podwójnych nawiasów.

lista1$imie

[1] "Jan"

In [59]:
lista1[[2]]

[1] "Jan"

In [60]:
lista1[2]

$imie
[1] "Jan"

In [61]:
lista1$przedmiot <- "WAD"
lapply(lista1, toupper)

$lp
[1] "1"

$imie
[1] "JAN"

$nazwisko
[1] "KOWALSKI"

$oceny
[1] "4"   "3.5" "5"  

$przedmiot
[1] "WAD"

### Ramki danych
Ramki danych stanowią struktury danych przypominające tabele z relacyjnych baz danych. Są one szczególnym typem listy. Reprezentują macierze o różnych typach kolumn. W odniesieniu do ramek danych można używać funkcji odnoszących się do list i do macierzy.

Do tworzenia prostej ramki danych można użyć funkcji `data.frame()`.

In [62]:
# Stwórz ramkę danych, a następnie sprawdź jej atrybuty oraz liczbę wierszy i kolumn.

dane <- data.frame(rok = c(2020, 2020, 2021, NA, 2022),
                   pora.roku = c("lato", "jesien", "lato", "jesien", "wiosna"),
                   maks.temp = c(32, 21, 33, 15, 22))
dane

rok  pora.roku maks.temp
1 2020 lato      32       
2 2020 jesien    21       
3 2021 lato      33       
4   NA jesien    15       
5 2022 wiosna    22

In [63]:
attributes(dane)

$names
[1] "rok"       "pora.roku" "maks.temp"

$class
[1] "data.frame"

$row.names
[1] 1 2 3 4 5

In [64]:
nrow(dane)

[1] 5

In [65]:
ncol(dane)

[1] 3

In [66]:
# Usuń wszystkie wiersze, w których występuje NA.

pelne <- complete.cases(dane)
dane <- dane[pelne,]
dane

rok  pora.roku maks.temp
1 2020 lato      32       
2 2020 jesien    21       
3 2021 lato      33       
5 2022 wiosna    22

In [67]:
# Przekonwertuj ramkę danych na macierz.
class(dane)

[1] "data.frame"

In [68]:
m <- data.matrix(dane)
m

rok  pora.roku maks.temp
1 2020 2         32       
2 2020 1         21       
3 2021 2         33       
5 2022 3         22

In [69]:
class(m)

[1] "matrix" "array"

In [70]:
# Przeanalizuj działanie następujących poleceń:

dane[dane$maks.temp > 30,]

rok  pora.roku maks.temp
1 2020 lato      32       
3 2021 lato      33

In [71]:
attach(dane)
maks.temp

[1] 32 21 33 22

In [72]:
dane[pora.roku != "lato" & maks.temp > 20,]

rok  pora.roku maks.temp
2 2020 jesien    21       
5 2022 wiosna    22

In [73]:
subset(dane, rok == 2020)

rok  pora.roku maks.temp
1 2020 lato      32       
2 2020 jesien    21

In [74]:
dane$min.temp <- c(18, 7, 16, -1)
dane

rok  pora.roku maks.temp min.temp
1 2020 lato      32        18      
2 2020 jesien    21         7      
3 2021 lato      33        16      
5 2022 wiosna    22        -1

In [75]:
data()

Data sets in package ‘datasets’:

AirPassengers           Monthly Airline Passenger Numbers 1949-1960
BJsales                 Sales Data with Leading Indicator
BJsales.lead (BJsales)
                        Sales Data with Leading Indicator
BOD                     Biochemical Oxygen Demand
CO2                     Carbon Dioxide Uptake in Grass Plants
ChickWeight             Weight versus age of chicks on different diets
DNase                   Elisa assay of DNase
EuStockMarkets          Daily Closing Prices of Major European Stock
                        Indices, 1991-1998
Formaldehyde            Determination of Formaldehyde
HairEyeColor            Hair and Eye Color of Statistics Students
Harman23.cor            Harman Example 2.3
Harman74.cor            Harman Example 7.4
Indometh                Pharmacokinetics of Indomethacin
InsectSprays            Effectiveness of Insect Sprays
JohnsonJohnson          Quarterly Earnings per Johnson & Johnson Share
LakeHuron               Level 

In [76]:
data("iris")
head(iris, 5)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa

### Instrukcje sterujące

In [77]:
# Przeanalizuj działanie poniższych pętli `for`. W tym celu wykorzystamy wektor z nazwami miesięcy,
# dostępny w podstawowych pakietach R.

for (i in month.name) {
  print(i)
}


[1] "January"
[1] "February"
[1] "March"
[1] "April"
[1] "May"
[1] "June"
[1] "July"
[1] "August"
[1] "September"
[1] "October"
[1] "November"
[1] "December"


In [78]:
for (i in 1:8) {
  print(month.name[i])
}

[1] "January"
[1] "February"
[1] "March"
[1] "April"
[1] "May"
[1] "June"
[1] "July"
[1] "August"


In [79]:
v <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
for (i in seq_along(v)) {
  print(month.name[i])
}

[1] "January"
[1] "February"
[1] "March"
[1] "April"
[1] "May"
[1] "June"
[1] "July"
[1] "August"
[1] "September"
[1] "October"


In [80]:
# Przeanalizuj działanie poniższej pętli `while`.

i <- 1
while (i <= 10) {
  print(i)
  i <- i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [81]:
# Przeanalizuj działanie poniższej pętli `repeat`. Zwróć uwagę na strukturę if-else, next oraz break.

i <- 1
repeat {
  i <- i + 1
  if(i == 11)
    break
  else if(i == 5)
    next
  else
    print(i)
}

[1] 2
[1] 3
[1] 4
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


### Funkcje

In [82]:
# Utwórz funkcję obliczającą wartość funkcji liniowej w punkcie x o podanych parametrach a i b,
# a następnie wyświetl wprowadzoną funkcję.

y <- function(x, a=1, b=0) {
  a * x + b
}

y

function (x, a = 1, b = 0) 
{
    a * x + b
}

In [83]:
# Spróbuj wywołać funkcję y() bez parametrów. Następnie wywołaj ją ponownie, wprowadzając tylko argument x.

# y()

In [84]:
y(1)

[1] 1

In [85]:
# Wywołaj funkcję z parametrami x=1, a=2, b=3. Zwróć uwagę na różne sposoby wywoływania funkcji
# - w jaki sposób odbywa się dopasowanie argumentów.

y(1, 2, 3)

[1] 5

In [86]:
y(b=3, a=2, x=1)

[1] 5

In [87]:
y(b=3, 1, a=2)

[1] 5

## Przygotowanie danych pomiarowych
Wykorzystywane w ćwiczeniach pliki danych zawierają uśrednione dane stanu powietrza w sierpniu i wrześniu 2023, pochodzące ze strony Głównego Inspektoratu Ochrony Środowiska dla stacji pomiarowej Kraków, al. Krasińskiego.

### Wczytywanie danych

In [88]:
# Wczytaj plik z danymi pomiarowymi z sierpnia 2023 roku i zapisz jako obiekt tibble o nazwie pomiary_sierpien

library(tidyverse)
pomiary_sierpien <- read_csv("dane/dane_sierpien.csv",
                             col_types = cols(...1 = col_skip()))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
New names:
• `` -> `...1`


In [89]:
# Wczytaj plik z danymi pomiarowymi z września 2023 i zapisz jako obiekt tibble o nazwie pomiary_wrzesien.

pomiary_wrzesien <- read_csv("dane/dane_wrzesien.csv",
                             col_types = cols(...1 = col_skip()))

New names:
• `` -> `...1`


In [90]:
class(pomiary_wrzesien)

[1] "spec_tbl_df" "tbl_df"      "tbl"         "data.frame"

In [91]:
glimpse(pomiary_sierpien)

Rows: 31
Columns: 10
$ PM25    <dbl> 11.760870, 8.295833, 8.383333, 10.000000, 11.295833, 7.333333,…
$ PM10    <dbl> 25.04348, 18.43750, 22.74583, 24.69583, 18.46667, 11.04583, 12…
$ NO2     <dbl> 44.57391, 36.24583, 50.06087, 47.40000, 36.00000, 21.67917, 21…
$ NO      <dbl> 38.83478, 22.17083, 36.19583, 38.62500, 26.02500, 19.16667, 17…
$ NOx     <dbl> 104.10870, 70.24167, 107.93913, 106.61667, 75.90417, 51.07500,…
$ CO      <dbl> 0.5956522, 0.5208333, 0.6347826, 0.6125000, 0.6041667, 0.51250…
$ C6H6    <dbl> 0.4652174, 0.3375000, 0.4782609, 0.4708333, 0.3863636, 0.35000…
$ rok     <dbl> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 20…
$ miesiac <dbl> 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,…
$ dzien   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…


In [92]:
glimpse(pomiary_wrzesien)

Rows: 30
Columns: 10
$ PM25    <dbl> 10.256522, 8.695652, 12.266667, 12.333333, 13.645833, 16.19166…
$ PM10    <dbl> 19.41739, 13.83913, 18.20833, 24.74583, 24.44583, 29.37083, 37…
$ NO2     <dbl> 40.28696, 35.57826, 32.40417, 40.05833, 51.07500, 54.46667, 58…
$ NO      <dbl> 33.73478, 27.31667, 27.14583, 29.18750, 48.97917, 51.78750, 58…
$ NOx     <dbl> 92.01304, 75.95000, 74.03750, 84.80000, 126.15417, 133.87083, …
$ CO      <dbl> 0.5000000, 0.5521739, 0.5458333, 0.4833333, 0.6000000, 0.63750…
$ C6H6    <dbl> 0.4347826, 0.4791667, 0.4875000, 0.3958333, 0.6958333, 0.81666…
$ rok     <dbl> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 20…
$ miesiac <dbl> 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,…
$ dzien   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…


In [93]:
# Połącz wczytanie dane zapisując je jako `powietrze`. Do połączenia danych wykorzystaj funkcję `rbind`.

powietrze <- rbind(pomiary_sierpien, pomiary_wrzesien)
glimpse(powietrze)

Rows: 61
Columns: 10
$ PM25    <dbl> 11.760870, 8.295833, 8.383333, 10.000000, 11.295833, 7.333333,…
$ PM10    <dbl> 25.04348, 18.43750, 22.74583, 24.69583, 18.46667, 11.04583, 12…
$ NO2     <dbl> 44.57391, 36.24583, 50.06087, 47.40000, 36.00000, 21.67917, 21…
$ NO      <dbl> 38.83478, 22.17083, 36.19583, 38.62500, 26.02500, 19.16667, 17…
$ NOx     <dbl> 104.10870, 70.24167, 107.93913, 106.61667, 75.90417, 51.07500,…
$ CO      <dbl> 0.5956522, 0.5208333, 0.6347826, 0.6125000, 0.6041667, 0.51250…
$ C6H6    <dbl> 0.4652174, 0.3375000, 0.4782609, 0.4708333, 0.3863636, 0.35000…
$ rok     <dbl> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 20…
$ miesiac <dbl> 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,…
$ dzien   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…


### Przekształcanie danych

In [94]:
# Wypisz i przeanalizuj nazwy kolumn, a następnie zmień nazwy na bardziej czytelne i wypisz pierwsze wiersze.

names(powietrze)

[1] "PM25"    "PM10"    "NO2"     "NO"      "NOx"     "CO"      "C6H6"   
 [8] "rok"     "miesiac" "dzien"

In [95]:
names(powietrze)[1:7] <- c("PM25", "PM10", "NO2", "NO", "NOx", "CO", "C6H6")
head(powietrze)

PM25      PM10     NO2      NO       NOx       CO        C6H6      rok 
1 11.760870 25.04348 44.57391 38.83478 104.10870 0.5956522 0.4652174 2023
2  8.295833 18.43750 36.24583 22.17083  70.24167 0.5208333 0.3375000 2023
3  8.383333 22.74583 50.06087 36.19583 107.93913 0.6347826 0.4782609 2023
4 10.000000 24.69583 47.40000 38.62500 106.61667 0.6125000 0.4708333 2023
5 11.295833 18.46667 36.00000 26.02500  75.90417 0.6041667 0.3863636 2023
6  7.333333 11.04583 21.67917 19.16667  51.07500 0.5125000 0.3500000 2023
  miesiac dzien
1 8       1    
2 8       2    
3 8       3    
4 8       4    
5 8       5    
6 8       6

In [96]:
# Wyświetl podsumowanie danych za pomocą poniższych funkcji:

summary(powietrze)

      PM25             PM10            NO2              NO       
 Min.   : 4.987   Min.   :11.05   Min.   :21.20   Min.   :16.01  
 1st Qu.:11.700   1st Qu.:20.14   1st Qu.:35.63   1st Qu.:25.12  
 Median :15.033   Median :25.27   Median :42.59   Median :30.89  
 Mean   :15.735   Mean   :27.07   Mean   :42.70   Mean   :36.01  
 3rd Qu.:20.429   3rd Qu.:34.17   3rd Qu.:51.08   3rd Qu.:42.12  
 Max.   :28.462   Max.   :47.05   Max.   :60.34   Max.   :81.55  
      NOx               CO              C6H6             rok      
 Min.   : 48.71   Min.   :0.4167   Min.   :0.1958   Min.   :2023  
 1st Qu.: 75.95   1st Qu.:0.5522   1st Qu.:0.3958   1st Qu.:2023  
 Median : 90.16   Median :0.5958   Median :0.4792   Median :2023  
 Mean   : 97.91   Mean   :0.6361   Mean   :0.5562   Mean   :2023  
 3rd Qu.:110.21   3rd Qu.:0.6478   3rd Qu.:0.6958   3rd Qu.:2023  
 Max.   :178.57   Max.   :3.0375   Max.   :1.0917   Max.   :2023  
    miesiac          dzien      
 Min.   :8.000   Min.   : 1.00  
 1s

In [97]:
str(powietrze)

spc_tbl_ [61 × 10] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ PM25   : num [1:61] 11.76 8.3 8.38 10 11.3 ...
 $ PM10   : num [1:61] 25 18.4 22.7 24.7 18.5 ...
 $ NO2    : num [1:61] 44.6 36.2 50.1 47.4 36 ...
 $ NO     : num [1:61] 38.8 22.2 36.2 38.6 26 ...
 $ NOx    : num [1:61] 104.1 70.2 107.9 106.6 75.9 ...
 $ CO     : num [1:61] 0.596 0.521 0.635 0.613 0.604 ...
 $ C6H6   : num [1:61] 0.465 0.338 0.478 0.471 0.386 ...
 $ rok    : num [1:61] 2023 2023 2023 2023 2023 ...
 $ miesiac: num [1:61] 8 8 8 8 8 8 8 8 8 8 ...
 $ dzien  : num [1:61] 1 2 3 4 5 6 7 8 9 10 ...
 - attr(*, "spec")=
  .. cols(
  ..   ...1 = col_skip(),
  ..   PM25 = col_double(),
  ..   PM10 = col_double(),
  ..   NO2 = col_double(),
  ..   NO = col_double(),
  ..   NOx = col_double(),
  ..   CO = col_double(),
  ..   C6H6 = col_double(),
  ..   rok = col_double(),
  ..   miesiac = col_double(),
  ..   dzien = col_double()
  .. )
 - attr(*, "problems")=<externalptr> 


In [98]:
quantile(powietrze$PM25, probs=seq(0,1,0.1), na.rm=TRUE)

0%       10%       20%       30%       40%       50%       60%       70% 
 4.987500  8.295833 10.000000 11.945833 13.645833 15.033333 16.941667 18.866667 
      80%       90%      100% 
21.178261 25.266667 28.462500

In [99]:
# Wyświetl typ danych poszczególnych kolumn.

for(i in names(powietrze)) print(class(powietrze[[i]]))

[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"
[1] "numeric"


In [100]:
# Zaokrąglij wyniki pomiarów do dwóch miejsc po przecinku.

powietrze[,1:7] <- round(powietrze[,1:7], 2)
head(powietrze)

PM25  PM10  NO2   NO    NOx    CO   C6H6 rok  miesiac dzien
1 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023 8       1    
2  8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023 8       2    
3  8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023 8       3    
4 10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023 8       4    
5 11.30 18.47 36.00 26.02  75.90 0.60 0.39 2023 8       5    
6  7.33 11.05 21.68 19.17  51.08 0.51 0.35 2023 8       6

In [101]:
# Stwórz nową kolumnę, w której zapiszesz datę każdego pomiaru wykorzystując kolumny: `dzien`, `miesiac` oraz `rok``.

powietrze$data <- as.Date(paste(powietrze$rok, powietrze$miesiac,
                                powietrze$dzien, sep="- "))
powietrze <- powietrze[,-(8:10)]
head(powietrze)

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01
2  8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023-08-02
3  8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03
4 10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04
5 11.30 18.47 36.00 26.02  75.90 0.60 0.39 2023-08-05
6  7.33 11.05 21.68 19.17  51.08 0.51 0.35 2023-08-06

In [102]:
# Przeanalizuj działanie poniższych funkcji związanych z typem `Date`:

today <- Sys.Date()
days <- julian(today)
format(today, "Dzisiaj jest %A (%d %B %y)")

[1] "Dzisiaj jest Wednesday (02 October 24)"

In [103]:
weekdays(today)

[1] "Wednesday"

In [104]:
as.Date(c("01.03.20"),"%d.%m.%y")

[1] "2020-03-01"

In [105]:
diff <- as.numeric(today - powietrze$data)
diff

[1] 428 427 426 425 424 423 422 421 420 419 418 417 416 415 414 413 412 411 410
[20] 409 408 407 406 405 404 403 402 401 400 399 398 397 396 395 394 393 392 391
[39] 390 389 388 387 386 385 384 383 382 381 380 379 378 377 376 375 374 373 372
[58] 371 370 369 368

In [106]:
# Sprawdź, w jaki sposób można wyświetlić konkretne wiersze:

head(powietrze, 5)

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01
2  8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023-08-02
3  8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03
4 10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04
5 11.30 18.47 36.00 26.02  75.90 0.60 0.39 2023-08-05

In [107]:
powietrze[2:3,]

PM25 PM10  NO2   NO    NOx    CO   C6H6 data      
1 8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023-08-02
2 8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03

In [108]:
powietrze[seq(1, 31, by=5), ]

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01
2  7.33 11.05 21.68 19.17  51.08 0.51 0.35 2023-08-06
3 14.11 25.50 46.44 29.56  91.77 0.56 0.48 2023-08-11
4 22.84 39.57 51.76 30.82  98.99 0.68 0.52 2023-08-16
5 28.46 44.70 46.71 25.49  85.82 0.70 0.48 2023-08-21
6 15.80 26.66 39.78 23.25  75.45 0.60 0.39 2023-08-26
7 11.84 20.14 31.63 24.70  69.46 0.44 0.35 2023-08-31

In [109]:
tail(powietrze)

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1 14.87 24.68 34.70 41.03  97.62 0.52 0.55 2023-09-25
2 20.52 35.74 42.83 61.22 136.71 0.69 0.77 2023-09-26
3 22.40 40.54 54.05 58.90 141.76 0.73 0.92 2023-09-27
4 22.01 42.59 54.23 77.60 173.21 0.78 0.95 2023-09-28
5 20.43 37.56 53.53 81.55 178.57 0.76 0.82 2023-09-29
6 18.87 28.12 35.67 64.76 134.96 0.73 0.73 2023-09-30

In [110]:
# Sprawdź, czy zmienna `PM25` zawiera brakujące dane.

any(is.na(powietrze$PM25))
!all(!is.na(powietrze$PM25))

[1] FALSE

[1] FALSE

In [111]:
# Wyświetl wszystkie dane, dla których `PM10` przekracza wartość 20.
# Zwróć uwagę, że funkcja `which()` sprawia, że nie wyświetlają się wiersze, dla których `PM10` przyjmuje wartość `NA`.

powietrze[(powietrze$PM10 > 20),]

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1  11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01
2   8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03
3  10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04
4  11.70 20.69 40.60 24.98  78.89 0.50 0.36 2023-08-10
5  14.11 25.50 46.44 29.56  91.77 0.56 0.48 2023-08-11
6  15.21 25.27 46.76 23.23  82.36 0.58 0.46 2023-08-12
7  15.60 25.22 39.52 25.12  79.68 0.61 0.49 2023-08-13
8  16.94 30.36 48.56 26.48  89.20 0.61 0.42 2023-08-14
9  20.64 33.34 37.08 20.39  68.35 0.62 0.51 2023-08-15
10 22.84 39.57 51.76 30.82  98.99 0.68 0.52 2023-08-16
11 18.80 34.17 45.54 28.41  89.10 0.60 0.53 2023-08-17
12 17.13 31.02 43.39 28.32  88.69 0.59 0.47 2023-08-18
13 18.93 28.18 34.96 21.90  68.56 0.60 0.39 2023-08-19
14 21.84 31.13 32.15 16.01  56.69 0.59 0.37 2023-08-20
15 28.46 44.70 46.71 25.49  85.82 0.70 0.48 2023-08-21
16 17.43 31.93 53.86 26.97  95.22 0.60 0.57 2023-08-22
17 25.27 37.15 42.59 20.65  75.60 0.59 0.46 2023-08-23
18 18.18 30.22 51.88 23.24  87.51 0.59 0.49 2023-08-24
19 23.05 42.98 54.96 32.09 104.21 0.69 0.82 2023-08-25
20 15.80 26.66 39.78 23.25  75.45 0.60 0.39 2023-08-26
21 13.89 20.74 31.65 17.87  59.06 0.58 0.39 2023-08-27
22 12.51 20.93 33.74 28.63  79.54 0.58 0.38 2023-08-28
23 15.03 24.92 35.63 34.48  88.49 0.62 0.48 2023-08-29
24 13.00 20.34 24.91 24.24  65.40 0.51 0.40 2023-08-30
25 11.84 20.14 31.63 24.70  69.46 0.44 0.35 2023-08-31
26 12.33 24.75 40.06 29.19  84.80 0.48 0.40 2023-09-04
27 13.65 24.45 51.08 48.98 126.15 0.60 0.70 2023-09-05
28 16.19 29.37 54.47 51.79 133.87 0.64 0.82 2023-09-06
29 21.18 37.08 58.63 58.48 145.75 0.70 0.99 2023-09-07
30 25.77 40.78 60.34 64.14 158.68 0.72 1.09 2023-09-08
31 26.55 36.32 53.00 42.51 118.19 0.68 0.91 2023-09-09
32 27.07 35.78 48.39 36.50 104.34 0.71 0.84 2023-09-10
33 20.21 34.22 48.63 34.36 101.31 0.58 0.59 2023-09-11
34 26.47 42.52 52.46 34.60 103.28 0.65 0.63 2023-09-12
35 28.10 47.05 52.71 30.89 100.06 0.61 0.59 2023-09-13
36 18.15 26.19 37.75 31.75  86.42 0.55 1.08 2023-09-16
37 15.68 29.02 50.08 59.76 141.71 0.66 0.77 2023-09-18
38 14.03 22.52 39.49 46.11 110.21 0.55 0.45 2023-09-19
39  9.70 22.92 53.74 66.64 155.92 0.67 0.90 2023-09-21
40 13.72 30.92 52.37 49.10 125.62 0.62 0.69 2023-09-22
41 14.87 24.68 34.70 41.03  97.62 0.52 0.55 2023-09-25
42 20.52 35.74 42.83 61.22 136.71 0.69 0.77 2023-09-26
43 22.40 40.54 54.05 58.90 141.76 0.73 0.92 2023-09-27
44 22.01 42.59 54.23 77.60 173.21 0.78 0.95 2023-09-28
45 20.43 37.56 53.53 81.55 178.57 0.76 0.82 2023-09-29
46 18.87 28.12 35.67 64.76 134.96 0.73 0.73 2023-09-30

In [112]:
powietrze[which(powietrze$PM10 > 20),]

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1  11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01
2   8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03
3  10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04
4  11.70 20.69 40.60 24.98  78.89 0.50 0.36 2023-08-10
5  14.11 25.50 46.44 29.56  91.77 0.56 0.48 2023-08-11
6  15.21 25.27 46.76 23.23  82.36 0.58 0.46 2023-08-12
7  15.60 25.22 39.52 25.12  79.68 0.61 0.49 2023-08-13
8  16.94 30.36 48.56 26.48  89.20 0.61 0.42 2023-08-14
9  20.64 33.34 37.08 20.39  68.35 0.62 0.51 2023-08-15
10 22.84 39.57 51.76 30.82  98.99 0.68 0.52 2023-08-16
11 18.80 34.17 45.54 28.41  89.10 0.60 0.53 2023-08-17
12 17.13 31.02 43.39 28.32  88.69 0.59 0.47 2023-08-18
13 18.93 28.18 34.96 21.90  68.56 0.60 0.39 2023-08-19
14 21.84 31.13 32.15 16.01  56.69 0.59 0.37 2023-08-20
15 28.46 44.70 46.71 25.49  85.82 0.70 0.48 2023-08-21
16 17.43 31.93 53.86 26.97  95.22 0.60 0.57 2023-08-22
17 25.27 37.15 42.59 20.65  75.60 0.59 0.46 2023-08-23
18 18.18 30.22 51.88 23.24  87.51 0.59 0.49 2023-08-24
19 23.05 42.98 54.96 32.09 104.21 0.69 0.82 2023-08-25
20 15.80 26.66 39.78 23.25  75.45 0.60 0.39 2023-08-26
21 13.89 20.74 31.65 17.87  59.06 0.58 0.39 2023-08-27
22 12.51 20.93 33.74 28.63  79.54 0.58 0.38 2023-08-28
23 15.03 24.92 35.63 34.48  88.49 0.62 0.48 2023-08-29
24 13.00 20.34 24.91 24.24  65.40 0.51 0.40 2023-08-30
25 11.84 20.14 31.63 24.70  69.46 0.44 0.35 2023-08-31
26 12.33 24.75 40.06 29.19  84.80 0.48 0.40 2023-09-04
27 13.65 24.45 51.08 48.98 126.15 0.60 0.70 2023-09-05
28 16.19 29.37 54.47 51.79 133.87 0.64 0.82 2023-09-06
29 21.18 37.08 58.63 58.48 145.75 0.70 0.99 2023-09-07
30 25.77 40.78 60.34 64.14 158.68 0.72 1.09 2023-09-08
31 26.55 36.32 53.00 42.51 118.19 0.68 0.91 2023-09-09
32 27.07 35.78 48.39 36.50 104.34 0.71 0.84 2023-09-10
33 20.21 34.22 48.63 34.36 101.31 0.58 0.59 2023-09-11
34 26.47 42.52 52.46 34.60 103.28 0.65 0.63 2023-09-12
35 28.10 47.05 52.71 30.89 100.06 0.61 0.59 2023-09-13
36 18.15 26.19 37.75 31.75  86.42 0.55 1.08 2023-09-16
37 15.68 29.02 50.08 59.76 141.71 0.66 0.77 2023-09-18
38 14.03 22.52 39.49 46.11 110.21 0.55 0.45 2023-09-19
39  9.70 22.92 53.74 66.64 155.92 0.67 0.90 2023-09-21
40 13.72 30.92 52.37 49.10 125.62 0.62 0.69 2023-09-22
41 14.87 24.68 34.70 41.03  97.62 0.52 0.55 2023-09-25
42 20.52 35.74 42.83 61.22 136.71 0.69 0.77 2023-09-26
43 22.40 40.54 54.05 58.90 141.76 0.73 0.92 2023-09-27
44 22.01 42.59 54.23 77.60 173.21 0.78 0.95 2023-09-28
45 20.43 37.56 53.53 81.55 178.57 0.76 0.82 2023-09-29
46 18.87 28.12 35.67 64.76 134.96 0.73 0.73 2023-09-30

In [113]:
# Wyświetl wszystkie dane, dla których `PM10` przekracza poziom 25 lub `PM25` jest poniżej poziomu 10. Zwróć uwagę na znak logiczny (`|` - _lub_, `&` - _i_).

powietrze[which(powietrze$PM10 > 25 | powietrze$PM25 < 10),]

PM25  PM10  NO2   NO    NOx    CO   C6H6 data      
1  11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01
2   8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023-08-02
3   8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03
4   7.33 11.05 21.68 19.17  51.08 0.51 0.35 2023-08-06
5   4.99 12.08 21.20 17.95  48.71 0.42 0.20 2023-08-07
6   6.00 14.38 30.77 19.87  62.57 0.43 0.27 2023-08-08
7   6.67 15.62 32.27 27.74  74.78 0.46 0.28 2023-08-09
8  14.11 25.50 46.44 29.56  91.77 0.56 0.48 2023-08-11
9  15.21 25.27 46.76 23.23  82.36 0.58 0.46 2023-08-12
10 15.60 25.22 39.52 25.12  79.68 0.61 0.49 2023-08-13
11 16.94 30.36 48.56 26.48  89.20 0.61 0.42 2023-08-14
12 20.64 33.34 37.08 20.39  68.35 0.62 0.51 2023-08-15
13 22.84 39.57 51.76 30.82  98.99 0.68 0.52 2023-08-16
14 18.80 34.17 45.54 28.41  89.10 0.60 0.53 2023-08-17
15 17.13 31.02 43.39 28.32  88.69 0.59 0.47 2023-08-18
16 18.93 28.18 34.96 21.90  68.56 0.60 0.39 2023-08-19
17 21.84 31.13 32.15 16.01  56.69 0.59 0.37 2023-08-20
18 28.46 44.70 46.71 25.49  85.82 0.70 0.48 2023-08-21
19 17.43 31.93 53.86 26.97  95.22 0.60 0.57 2023-08-22
20 25.27 37.15 42.59 20.65  75.60 0.59 0.46 2023-08-23
21 18.18 30.22 51.88 23.24  87.51 0.59 0.49 2023-08-24
22 23.05 42.98 54.96 32.09 104.21 0.69 0.82 2023-08-25
23 15.80 26.66 39.78 23.25  75.45 0.60 0.39 2023-08-26
24  8.70 13.84 35.58 27.32  75.95 0.55 0.48 2023-09-02
25 16.19 29.37 54.47 51.79 133.87 0.64 0.82 2023-09-06
26 21.18 37.08 58.63 58.48 145.75 0.70 0.99 2023-09-07
27 25.77 40.78 60.34 64.14 158.68 0.72 1.09 2023-09-08
28 26.55 36.32 53.00 42.51 118.19 0.68 0.91 2023-09-09
29 27.07 35.78 48.39 36.50 104.34 0.71 0.84 2023-09-10
30 20.21 34.22 48.63 34.36 101.31 0.58 0.59 2023-09-11
31 26.47 42.52 52.46 34.60 103.28 0.65 0.63 2023-09-12
32 28.10 47.05 52.71 30.89 100.06 0.61 0.59 2023-09-13
33  8.87 14.67 38.97 25.20  77.62 0.46 0.31 2023-09-14
34  8.78 16.76 46.00 42.12 110.58 0.50 0.52 2023-09-15
35 18.15 26.19 37.75 31.75  86.42 0.55 1.08 2023-09-16
36 15.68 29.02 50.08 59.76 141.71 0.66 0.77 2023-09-18
37  7.64 17.78 39.02 58.05 128.04 0.60 0.49 2023-09-20
38  9.70 22.92 53.74 66.64 155.92 0.67 0.90 2023-09-21
39 13.72 30.92 52.37 49.10 125.62 0.62 0.69 2023-09-22
40  7.47 11.70 34.59 35.11  87.50 3.04 0.39 2023-09-24
41 20.52 35.74 42.83 61.22 136.71 0.69 0.77 2023-09-26
42 22.40 40.54 54.05 58.90 141.76 0.73 0.92 2023-09-27
43 22.01 42.59 54.23 77.60 173.21 0.78 0.95 2023-09-28
44 20.43 37.56 53.53 81.55 178.57 0.76 0.82 2023-09-29
45 18.87 28.12 35.67 64.76 134.96 0.73 0.73 2023-09-30

In [114]:
# Przyporządkuj grupy do poszczególnych pomiarów:

# `L` dla `PM25` < kwantyla rzędu 1/4
# `M` dla `PM25` >= kwantyla rzędu 2/4
# `H` dla `PM25` >= kwantyla rzędu 3/4

powietrze[which(powietrze$PM25 < quantile(powietrze$PM25, na.rm=T, probs=0.25)),
          "poziom_PM25"] <- "L"
powietrze[which(powietrze$PM25 >= quantile(powietrze$PM25, na.rm=T, probs=0.25)
                & powietrze$PM25 <= quantile(powietrze$PM25, na.rm=T, probs=0.75)),
          "poziom_PM25"] <- "M"
powietrze[which(powietrze$PM25 > quantile(powietrze$PM25, na.rm=T, probs=0.75)),
          "poziom_PM25"] <- "H"

head(powietrze)

PM25  PM10  NO2   NO    NOx    CO   C6H6 data       poziom_PM25
1 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01 M          
2  8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023-08-02 L          
3  8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03 L          
4 10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04 L          
5 11.30 18.47 36.00 26.02  75.90 0.60 0.39 2023-08-05 L          
6  7.33 11.05 21.68 19.17  51.08 0.51 0.35 2023-08-06 L

In [115]:
# Podobnie przyporządkuj grupy ze względu na wartość `PM10`:

powietrze[which(powietrze$PM10 < quantile(powietrze$PM10, na.rm=T, probs=0.25)),
          "poziom_PM10"] <- "L"
powietrze[which(powietrze$PM10 >= quantile(powietrze$PM10, na.rm=T, probs=0.25)
                & powietrze$PM10 <= quantile(powietrze$PM10, na.rm=T, probs=0.75)),
          "poziom_PM10"] <- "M"
powietrze[which(powietrze$PM10 > quantile(powietrze$PM10, na.rm=T, probs=0.75)),
          "poziom_PM10"] <- "H"
head(powietrze)

PM25  PM10  NO2   NO    NOx    CO   C6H6 data       poziom_PM25 poziom_PM10
1 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01 M           M          
2  8.30 18.44 36.25 22.17  70.24 0.52 0.34 2023-08-02 L           L          
3  8.38 22.75 50.06 36.20 107.94 0.63 0.48 2023-08-03 L           M          
4 10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04 L           M          
5 11.30 18.47 36.00 26.02  75.90 0.60 0.39 2023-08-05 L           L          
6  7.33 11.05 21.68 19.17  51.08 0.51 0.35 2023-08-06 L           L

In [116]:
# Wyświetl liczebności grup.

table(powietrze$poziom_PM25, powietrze$poziom_PM10)

   
     H  L  M
  H 13  0  2
  L  0 12  3
  M  2  3 26

In [117]:
# Posortuj dane wartości `PM25` od największej do najmniejszej.

sort(powietrze$PM25, decreasing=TRUE)

[1] 28.46 28.10 27.07 26.55 26.47 25.77 25.27 23.05 22.84 22.40 22.01 21.84
[13] 21.18 20.64 20.52 20.43 20.21 18.93 18.87 18.80 18.18 18.15 17.43 17.13
[25] 16.94 16.19 15.80 15.68 15.60 15.21 15.03 14.87 14.11 14.03 13.89 13.72
[37] 13.65 13.12 13.00 12.51 12.33 12.27 11.95 11.84 11.76 11.70 11.30 10.26
[49] 10.00  9.70  8.87  8.78  8.70  8.38  8.30  7.64  7.47  7.33  6.67  6.00
[61]  4.99

In [118]:
# Posortuj ramkę danych wg `PM25` od największej do najmniejszej wartości.

powietrze[order(powietrze$PM25, decreasing = T),]

PM25  PM10  NO2   NO    NOx    CO   C6H6 data       poziom_PM25 poziom_PM10
1  28.46 44.70 46.71 25.49  85.82 0.70 0.48 2023-08-21 H           H          
2  28.10 47.05 52.71 30.89 100.06 0.61 0.59 2023-09-13 H           H          
3  27.07 35.78 48.39 36.50 104.34 0.71 0.84 2023-09-10 H           H          
4  26.55 36.32 53.00 42.51 118.19 0.68 0.91 2023-09-09 H           H          
5  26.47 42.52 52.46 34.60 103.28 0.65 0.63 2023-09-12 H           H          
6  25.77 40.78 60.34 64.14 158.68 0.72 1.09 2023-09-08 H           H          
7  25.27 37.15 42.59 20.65  75.60 0.59 0.46 2023-08-23 H           H          
8  23.05 42.98 54.96 32.09 104.21 0.69 0.82 2023-08-25 H           H          
9  22.84 39.57 51.76 30.82  98.99 0.68 0.52 2023-08-16 H           H          
10 22.40 40.54 54.05 58.90 141.76 0.73 0.92 2023-09-27 H           H          
11 22.01 42.59 54.23 77.60 173.21 0.78 0.95 2023-09-28 H           H          
12 21.84 31.13 32.15 16.01  56.69 0.59 0.37 2023-08-20 H           M          
13 21.18 37.08 58.63 58.48 145.75 0.70 0.99 2023-09-07 H           H          
14 20.64 33.34 37.08 20.39  68.35 0.62 0.51 2023-08-15 H           M          
15 20.52 35.74 42.83 61.22 136.71 0.69 0.77 2023-09-26 H           H          
16 20.43 37.56 53.53 81.55 178.57 0.76 0.82 2023-09-29 M           H          
17 20.21 34.22 48.63 34.36 101.31 0.58 0.59 2023-09-11 M           H          
18 18.93 28.18 34.96 21.90  68.56 0.60 0.39 2023-08-19 M           M          
19 18.87 28.12 35.67 64.76 134.96 0.73 0.73 2023-09-30 M           M          
20 18.80 34.17 45.54 28.41  89.10 0.60 0.53 2023-08-17 M           M          
21 18.18 30.22 51.88 23.24  87.51 0.59 0.49 2023-08-24 M           M          
22 18.15 26.19 37.75 31.75  86.42 0.55 1.08 2023-09-16 M           M          
23 17.43 31.93 53.86 26.97  95.22 0.60 0.57 2023-08-22 M           M          
24 17.13 31.02 43.39 28.32  88.69 0.59 0.47 2023-08-18 M           M          
25 16.94 30.36 48.56 26.48  89.20 0.61 0.42 2023-08-14 M           M          
26 16.19 29.37 54.47 51.79 133.87 0.64 0.82 2023-09-06 M           M          
27 15.80 26.66 39.78 23.25  75.45 0.60 0.39 2023-08-26 M           M          
28 15.68 29.02 50.08 59.76 141.71 0.66 0.77 2023-09-18 M           M          
29 15.60 25.22 39.52 25.12  79.68 0.61 0.49 2023-08-13 M           M          
30 15.21 25.27 46.76 23.23  82.36 0.58 0.46 2023-08-12 M           M          
⋮  ⋮     ⋮     ⋮     ⋮     ⋮      ⋮    ⋮    ⋮          ⋮           ⋮          
32 14.87 24.68 34.70 41.03  97.62 0.52 0.55 2023-09-25 M           M          
33 14.11 25.50 46.44 29.56  91.77 0.56 0.48 2023-08-11 M           M          
34 14.03 22.52 39.49 46.11 110.21 0.55 0.45 2023-09-19 M           M          
35 13.89 20.74 31.65 17.87  59.06 0.58 0.39 2023-08-27 M           M          
36 13.72 30.92 52.37 49.10 125.62 0.62 0.69 2023-09-22 M           M          
37 13.65 24.45 51.08 48.98 126.15 0.60 0.70 2023-09-05 M           M          
38 13.12 19.58 41.00 37.97  97.39 0.60 0.80 2023-09-17 M           L          
39 13.00 20.34 24.91 24.24  65.40 0.51 0.40 2023-08-30 M           M          
40 12.51 20.93 33.74 28.63  79.54 0.58 0.38 2023-08-28 M           M          
41 12.33 24.75 40.06 29.19  84.80 0.48 0.40 2023-09-04 M           M          
42 12.27 18.21 32.40 27.15  74.04 0.55 0.49 2023-09-03 M           L          
43 11.95 18.27 34.15 36.54  90.16 0.53 0.42 2023-09-23 M           L          
44 11.84 20.14 31.63 24.70  69.46 0.44 0.35 2023-08-31 M           M          
45 11.76 25.04 44.57 38.83 104.11 0.60 0.47 2023-08-01 M           M          
46 11.70 20.69 40.60 24.98  78.89 0.50 0.36 2023-08-10 M           M          
47 11.30 18.47 36.00 26.02  75.90 0.60 0.39 2023-08-05 L           L          
48 10.26 19.42 40.29 33.73  92.01 0.50 0.43 2023-09-01 L           L          
49 10.00 24.70 47.40 38.62 106.62 0.61 0.47 2023-08-04 L           M          
50  9.70 22.92 53.74 66.64 155.92 0.67 0.90 2023-09-2

Wykorzystaj pakiet `dplyr` oraz operator `%>%` i wykonaj następujące czynności:

- ogranicz wartości do tych z miesiąca sierpnia,
- ukryj kolumny `poziom_pm25` oraz `poziom_pm10`,
- wyznacz dni tygodnia,
- pogrupuj po dniu tygodnia
- wyświetl zestawienia wartości średnich `PM25` oraz `PM10` dla każdego tygodnia,
- posortuj zestawienie wg `PM25` od największej do najmniejszej wartości.

In [119]:
library(dplyr)
powietrze %>% #weź dane ze zbioru powietrze
  filter(month(data) == 8) %>% #pozostaw tylko dane z sierpnia
  select(-(poziom_PM25:poziom_PM10)) %>% #ukryj kolumny poziom_PM25 oraz poziom_PM10
  mutate(dzien_tyg=weekdays(data)) %>% #wyznacz dni tygodnia
  group_by(dzien_tyg) %>% #pogrupuj po dniu tygodnia
  summarize(srednie_PM25 = mean(PM25), srednie_PM10 = mean(PM10)) %>% #wyświetl
                                    #wartości średnie dla każdego dnia tygodnia
  arrange(desc(srednie_PM25)) #posortuj malejąco wg PM25

dzien_tyg srednie_PM25 srednie_PM10
1 Friday    16.0725      31.0500     
2 Monday    15.7250      27.0175     
3 Saturday  15.3100      24.6450     
4 Wednesday 15.2160      26.2240     
5 Sunday    14.6650      22.0350     
6 Tuesday   14.1720      25.9220     
7 Thursday  13.7800      25.5940

In [120]:
# Wykorzystując bibliotekę `reshape2` zapisz pomiar każdej wartości w osobnym wierszu tabeli,
# a następnie zamień tabelę, gdzie w jednym wierszu będą wyświetlone pomiary wszystkich wartości z 1 dnia.

library(reshape2)
powietrze_waska <- melt(powietrze, id=c("data"),
                        measure.vars=c("PM25", "PM10", "NO2", "NO", "NOx", "CO","C6H6"))
powietrze_waska


Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths




data       variable value
1   2023-08-01 PM25     11.76
2   2023-08-02 PM25      8.30
3   2023-08-03 PM25      8.38
4   2023-08-04 PM25     10.00
5   2023-08-05 PM25     11.30
6   2023-08-06 PM25      7.33
7   2023-08-07 PM25      4.99
8   2023-08-08 PM25      6.00
9   2023-08-09 PM25      6.67
10  2023-08-10 PM25     11.70
11  2023-08-11 PM25     14.11
12  2023-08-12 PM25     15.21
13  2023-08-13 PM25     15.60
14  2023-08-14 PM25     16.94
15  2023-08-15 PM25     20.64
16  2023-08-16 PM25     22.84
17  2023-08-17 PM25     18.80
18  2023-08-18 PM25     17.13
19  2023-08-19 PM25     18.93
20  2023-08-20 PM25     21.84
21  2023-08-21 PM25     28.46
22  2023-08-22 PM25     17.43
23  2023-08-23 PM25     25.27
24  2023-08-24 PM25     18.18
25  2023-08-25 PM25     23.05
26  2023-08-26 PM25     15.80
27  2023-08-27 PM25     13.89
28  2023-08-28 PM25     12.51
29  2023-08-29 PM25     15.03
30  2023-08-30 PM25     13.00
⋮   ⋮          ⋮        ⋮    
398 2023-09-01 C6H6     0.43 
399 2023-09-02 C6H6     0.48 
400 2023-09-03 C6H6     0.49 
401 2023-09-04 C6H6     0.40 
402 2023-09-05 C6H6     0.70 
403 2023-09-06 C6H6     0.82 
404 2023-09-07 C6H6     0.99 
405 2023-09-08 C6H6     1.09 
406 2023-09-09 C6H6     0.91 
407 2023-09-10 C6H6     0.84 
408 2023-09-11 C6H6     0.59 
409 2023-09-12 C6H6     0.63 
410 2023-09-13 C6H6     0.59 
411 2023-09-14 C6H6     0.31 
412 2023-09-15 C6H6     0.52 
413 2023-09-16 C6H6     1.08 
414 2023-09-17 C6H6     0.80 
415 2023-09-18 C6H6     0.77 
416 2023-09-19 C6H6     0.45 
417 2023-09-20 C6H6     0.49 
418 2023-09-21 C6H6     0.90 
419 2023-09-22 C6H6     0.69 
420 2023-09-23 C6H6     0.42 
421 2023-09-24 C6H6     0.39 
422 2023-09-25 C6H6     0.55 
423 2023-09-26 C6H6     0.77 
424 2023-09-27 C6H6     0.92 
425 2023-09-28 C6H6     0.95 
426 2023-09-29 C6H6     0.82 
427 2023-09-30 C6H6     0.73

In [121]:
dcast(powietrze_waska, data ~ variable)

data       PM25  PM10  NO2   NO    NOx    CO   C6H6
1  2023-08-01 11.76 25.04 44.57 38.83 104.11 0.60 0.47
2  2023-08-02  8.30 18.44 36.25 22.17  70.24 0.52 0.34
3  2023-08-03  8.38 22.75 50.06 36.20 107.94 0.63 0.48
4  2023-08-04 10.00 24.70 47.40 38.62 106.62 0.61 0.47
5  2023-08-05 11.30 18.47 36.00 26.02  75.90 0.60 0.39
6  2023-08-06  7.33 11.05 21.68 19.17  51.08 0.51 0.35
7  2023-08-07  4.99 12.08 21.20 17.95  48.71 0.42 0.20
8  2023-08-08  6.00 14.38 30.77 19.87  62.57 0.43 0.27
9  2023-08-09  6.67 15.62 32.27 27.74  74.78 0.46 0.28
10 2023-08-10 11.70 20.69 40.60 24.98  78.89 0.50 0.36
11 2023-08-11 14.11 25.50 46.44 29.56  91.77 0.56 0.48
12 2023-08-12 15.21 25.27 46.76 23.23  82.36 0.58 0.46
13 2023-08-13 15.60 25.22 39.52 25.12  79.68 0.61 0.49
14 2023-08-14 16.94 30.36 48.56 26.48  89.20 0.61 0.42
15 2023-08-15 20.64 33.34 37.08 20.39  68.35 0.62 0.51
16 2023-08-16 22.84 39.57 51.76 30.82  98.99 0.68 0.52
17 2023-08-17 18.80 34.17 45.54 28.41  89.10 0.60 0.53
18 2023-08-18 17.13 31.02 43.39 28.32  88.69 0.59 0.47
19 2023-08-19 18.93 28.18 34.96 21.90  68.56 0.60 0.39
20 2023-08-20 21.84 31.13 32.15 16.01  56.69 0.59 0.37
21 2023-08-21 28.46 44.70 46.71 25.49  85.82 0.70 0.48
22 2023-08-22 17.43 31.93 53.86 26.97  95.22 0.60 0.57
23 2023-08-23 25.27 37.15 42.59 20.65  75.60 0.59 0.46
24 2023-08-24 18.18 30.22 51.88 23.24  87.51 0.59 0.49
25 2023-08-25 23.05 42.98 54.96 32.09 104.21 0.69 0.82
26 2023-08-26 15.80 26.66 39.78 23.25  75.45 0.60 0.39
27 2023-08-27 13.89 20.74 31.65 17.87  59.06 0.58 0.39
28 2023-08-28 12.51 20.93 33.74 28.63  79.54 0.58 0.38
29 2023-08-29 15.03 24.92 35.63 34.48  88.49 0.62 0.48
30 2023-08-30 13.00 20.34 24.91 24.24  65.40 0.51 0.40
⋮  ⋮          ⋮     ⋮     ⋮     ⋮     ⋮      ⋮    ⋮   
32 2023-09-01 10.26 19.42 40.29 33.73  92.01 0.50 0.43
33 2023-09-02  8.70 13.84 35.58 27.32  75.95 0.55 0.48
34 2023-09-03 12.27 18.21 32.40 27.15  74.04 0.55 0.49
35 2023-09-04 12.33 24.75 40.06 29.19  84.80 0.48 0.40
36 2023-09-05 13.65 24.45 51.08 48.98 126.15 0.60 0.70
37 2023-09-06 16.19 29.37 54.47 51.79 133.87 0.64 0.82
38 2023-09-07 21.18 37.08 58.63 58.48 145.75 0.70 0.99
39 2023-09-08 25.77 40.78 60.34 64.14 158.68 0.72 1.09
40 2023-09-09 26.55 36.32 53.00 42.51 118.19 0.68 0.91
41 2023-09-10 27.07 35.78 48.39 36.50 104.34 0.71 0.84
42 2023-09-11 20.21 34.22 48.63 34.36 101.31 0.58 0.59
43 2023-09-12 26.47 42.52 52.46 34.60 103.28 0.65 0.63
44 2023-09-13 28.10 47.05 52.71 30.89 100.06 0.61 0.59
45 2023-09-14  8.87 14.67 38.97 25.20  77.62 0.46 0.31
46 2023-09-15  8.78 16.76 46.00 42.12 110.58 0.50 0.52
47 2023-09-16 18.15 26.19 37.75 31.75  86.42 0.55 1.08
48 2023-09-17 13.12 19.58 41.00 37.97  97.39 0.60 0.80
49 2023-09-18 15.68 29.02 50.08 59.76 141.71 0.66 0.77
50 2023-09-19 14.03 22.52 39.49 46.11 110.21 0.55 0.45
51 2023-09-20  7.64 17.78 39.02 58.05 128.04 0.60 0.49
52 2023-09-21  9.70 22.92 53.74 66.64 155.92 0.67 0.90
53 2023-09-22 13.72 30.92 52.37 49.10 125.62 0.62 0.69
54 2023-09-23 11.95 18.27 34.15 36.54  90.16 0.53 0.42
55 2023-09-24  7.47 11.70 34.59 35.11  87.50 3.04 0.39
56 2023-09-25 14.87 24.68 34.70 41.03  97.62 0.52 0.55
57 2023-09-26 20.52 35.74 42.83 61.22 136.71 0.69 0.77
58 2023-09-27 22.40 40.54 54.05 58.90 141.76 0.73 0.92
59 2023-09-28 22.01 42.59 54.23 77.60 173.21 0.78 0.95
60 2023-09-29 20.43 37.56 53.53 81.55 178.57 0.76 0.82
61 2023-09-30 18.87 28.12 35.67 64.76 134.96 0.73 0.73

## Zadania

1. Wczytaj dane pomiarowe z pliku `gios-pjp-data1.csv` i zapisz je jako obiekt `tibble`.

In [122]:
df <- read_csv("dane/gios-pjp-data1.csv", show_col_types = FALSE)
names(df)[2:8] <- c("PM25", "PM10", "NO2", "NO", "NOx", "CO", "C6H6")
df$date = date(df$Data)
df <- df[-1]
head(df)

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”


PM25 PM10 NO2  NO   NOx   CO  C6H6 date      
1 12.3 25.7 30.4 10.0  45.7 0.5 0.3  2023-08-01
2 14.0 27.4 31.9 23.4  67.7 0.5 0.4  2023-08-01
3 14.0 25.3 28.5 14.3  50.5 0.5 0.4  2023-08-01
4 14.0 29.3 23.4 27.7  65.8 0.5 0.4  2023-08-01
5 14.9 30.2 27.8 51.4 106.7 0.5 0.5  2023-08-01
6 17.2 39.1 42.2 85.5 173.2 0.7 0.7  2023-08-01

In [123]:
tail(df)

PM25 PM10 NO2  NO   NOx   CO  C6H6 date      
1  8.4 19.3 57.5 43.8 124.7 0.6 0.5  2023-08-31
2 10.3 22.0 52.8 50.9 130.9 0.8 0.8  2023-08-31
3 10.1 17.8 40.4 31.0  88.0 0.6 0.7  2023-08-31
4  9.4 16.5 37.7 25.6  77.0 0.5 0.6  2023-08-31
5 10.0 17.5 38.3 27.2  80.0 0.5 0.5  2023-08-31
6   NA   NA   NA   NA    NA  NA  NA  2023-09-01

In [124]:
df <- df[-nrow(df), ]
tail(df)

PM25 PM10 NO2  NO   NOx   CO  C6H6 date      
1  7.9 16.2 42.2 23.2  77.7 0.5 0.4  2023-08-31
2  8.4 19.3 57.5 43.8 124.7 0.6 0.5  2023-08-31
3 10.3 22.0 52.8 50.9 130.9 0.8 0.8  2023-08-31
4 10.1 17.8 40.4 31.0  88.0 0.6 0.7  2023-08-31
5  9.4 16.5 37.7 25.6  77.0 0.5 0.6  2023-08-31
6 10.0 17.5 38.3 27.2  80.0 0.5 0.5  2023-08-31

2. Utwórz nową ramkę danych, w której zapiszesz wartości średnie dobowe pomiarów.

In [125]:
# df.groupby(date).mean()
df_means <- df %>%
                group_by(date) %>%
                summarise(across(everything(), \(x) mean(x, na.rm=TRUE)))

head(df_means)

date       PM25      PM10     NO2      NO       NOx       CO        C6H6     
1 2023-08-01 11.760870 25.04348 44.57391 38.83478 104.10870 0.5956522 0.4652174
2 2023-08-02  8.295833 18.43750 36.24583 22.17083  70.24167 0.5208333 0.3375000
3 2023-08-03  8.383333 22.74583 50.06087 36.19583 107.93913 0.6347826 0.4782609
4 2023-08-04 10.000000 24.69583 47.40000 38.62500 106.61667 0.6125000 0.4708333
5 2023-08-05 11.295833 18.46667 36.00000 26.02500  75.90417 0.6041667 0.3863636
6 2023-08-06  7.333333 11.04583 21.67917 19.16667  51.07500 0.5125000 0.3500000

3. Na nowych danych oblicz wartość średnią dla zmiennej NO2, wyłącznie dla wybranego dnia tygodnia.

In [126]:
dayoftheweek <- "Wednesday"
df_means %>%
   filter(weekdays(date) == dayoftheweek) %>%
   summarize(mean(NO2))

mean(NO2)
1 37.55682

In [127]:
df_means$weekday <- weekdays(df_means$date)
custom_key <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
df_means %>%
    group_by(weekday) %>%
    summarise(mean(NO2)) %>%
    arrange(match(weekday, custom_key)) 

weekday   mean(NO2)
1 Monday    37.55249 
2 Tuesday   40.38199 
3 Wednesday 37.55682 
4 Thursday  43.94217 
5 Friday    48.04778 
6 Saturday  39.37604 
7 Sunday    31.24810

In [128]:
# EOF